name: api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup-go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: prepare
      run: make setup && make download

    - name: test
      run: make test

    - name: sec
      run: make sec

    - name: build
      run: make build
